apiVersion: v1
kind: Pod
metadata:
  name: cuda-dev
spec:
  restartPolicy: Always
  nodeSelector:
    compute.coreweave.com/node-pool: lukas-4h200-pool
  containers:
    - name: cuda
      image: nvcr.io/nvidia/tensorrt-llm/release:1.3.0rc6
      command: ["sleep"]
      args: ["infinity"]
      resources:
        limits:
          nvidia.com/gpu: 4
      volumeMounts:
        - name: workspace
          mountPath: /workspace
  volumes:
    - name: workspace
      persistentVolumeClaim:
        claimName: cuda-workspace
