apiVersion: v1
kind: Pod
metadata:
  name: cuda-dev
spec:
  restartPolicy: Always
  nodeSelector:
    compute.coreweave.com/node-pool: test-node-pool
  containers:
    - name: cuda
      image: nvidia/cuda:12.4.1-devel-ubuntu22.04
      command: ["sleep"]
      args: ["infinity"]
      resources:
        limits:
          nvidia.com/gpu: 1
      volumeMounts:
        - name: workspace
          mountPath: /workspace
  volumes:
    - name: workspace
      persistentVolumeClaim:
        claimName: cuda-workspace
